testing-library/jest-native

README.md, extend-expect.d.ts, jest.config.js, package.json, setup-tests.js, src/__tests__/to-be-disabled.js, src/__tests__/to-have-prop.js, src/to-be-disabled.js
**What**:
A jest preset meant to supercharge `native-testing-library`
**Why**:
I want the same "DOM" feel in `debug` output and snapshots as `dom-testing-library` gives you. I think the RN core team already has a good idea of the type of mocks they want in the bundled jest preset, so for now we'll create our own to emulate the feel we want.
Ultimately, I could totally see these mocks merging back into `react-native`, and _I hope it does_ but until then, I'd like to be able to use this functionality as soon as possible. If for no other reason than the delay of merged features in RN, I think this is necessary to get moving,
**How**:
This requires unmocking some things from the `react-native` preset and doing it ourself.
**Checklist**:
=> feat: support changes for native-testing-library preset

extend-expect.d.ts
**What**:
Fixes TypeScript failing to find extended expect methods
Closes #7 
**How**:
By default a `d.ts` file augments the global namespace. As soon as an `import` or `export` is used in the `d.ts` file it changes to a module definition. This makes it necessary to use `declare global {}` to add to the global namespace explicitly. In `jest-dom/extend-expect.d.ts` which the current implementation is based on there are no imports which, I believe, is why it works fine.
**Checklist**:
=> Merge extended matchers with the global namespace

src/__tests__/to-have-style.js, src/to-have-style.js
**What**: This fixes not being able to test components which receive nested arrays in their `style` prop.
**Why**: react-native allows nested array for the `style` prop. Although it's not explicity written in the [docs](https://facebook.github.io/react-native/docs/style) but TypeScript [typings for react-native](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdf01cf33d2db0f25558413ce3ba98b472c4dd07/types/react-native/index.d.ts#L1966) allow it and some libraries (at least [react-native-paper](https://github.com/callstack/react-native-paper)) are making use of them.
**How**: We flatten the `style` prop before using `mergeAll`
**Checklist**:
=> Support nested arrays in style prop

src/__tests__/to-be-disabled.js, src/to-be-disabled.js
**What**:
Enabling toBeDisabled matcher for TextInput elements
**Why**:
They were ignored before
**How**:
Just added TextInput as a valid disabled element
**Checklist**:
Hi! Thanks for this library first of all :)
So I have added some tests but I am having a weird problem with them. It looks like the element is passing as null for some reason. I've tried to update react native and testing library but the issue carries on happening. Wondering if you could help with this little bit and have the PR ready?
Thanks again
=> Enabling toBeDisabled matcher for TextInput elements

src/__tests__/to-have-style.js, src/to-have-style.js
**What**:
Now the matcher `toHaveStyle` can handle elements without style.
**Why**:
It's useful to check whether an element has a style or not when conditionally applying a style.
**How**:
I've added a default value `{}` to the `received` styles.
**Checklist**:
- [N/A] Documentation added to the [docs](https://github.com/testing-library/jest-native/README.md)
- [N/A] Typescript definitions updated
=> feat(toHaveStyle): handle when the prop style is undefined

README.md, src/__tests__/to-be-disabled.js, src/to-be-disabled.js
**What**:
This PR adds support to the prop `accessibilityState` to the matcher `toBeDisabled`
**Why**:
RN 0.62 removed the old prop `accessibilityStates` in favor of `accessibilityState`
https://reactnative.dev/blog/2020/03/26/version-0.62#breaking-changes
**How**:
I created a new condition `hasStateDisabled` to verify whether the prop `accessibilityState` has disabled in its value to be used together with the old condition for `accessibilityStates`.  Maybe in the future, we can deprecate and remove this.
**Checklist**:
- [N/A] Typescript definitions updated
=> feat: support RN 0.62 accessibilityState in toBeDisabled

package.json, src/__tests__/to-be-disabled.js, src/to-be-disabled.js
**What**:
Updated jest-native to support RN 0.63 Pressable component in toBeDisabled.
**Why**:
When testing a Pressable component the test always fails. 
**How**:
Updated dependencies to support RN 0.63. Added Pressable to supported Types.
**Checklist**:
Related to issue https://github.com/testing-library/jest-native/issues/23
=> feat: support RN 0.63 Pressable in toBeDisabled

README.md, src/__tests__/__snapshots__/to-have-style.js.snap, src/__tests__/to-have-style.js, src/to-have-style.js
**What**:
Adds ability for `.toHaveStyle()` to compare `transform` styles.
**Why**:
Previously, `.toHaveStyle()` would only operate on shallow style properties, but transforms are specified as an `object[]`. The transform values would then be compared using strict equality and as such would never pass.
Furthermore, the diffs would serialize the transform values as `[object Object]` making both sides appear to be equal. 
Ultimately, the test would fail regardless but the diff would tell us that everything is fine.
**How**:
We're now properly handling any style properties with `object[]` values and correctly serializing the `expected` and `received` passed to `jestDiff`. In both cases using recursion to perform the deep checks.
**Checklist**: …
=> .toHaveStyle() to support transform styles

.all-contributorsrc, README.md, src/__tests__/to-have-text-content.js, src/to-have-text-content.js
**What**:
Trying to check for text content in a text node that contains conditional rendering can fail using specifc regex.
For example:
```
<Text testID="parent>
<Text>Shown</Text>
{false && <Text>Hidden</Text>}
<Text>
expect(getByTestID('parent')).toHaveTextContent(/^Shown$/)
```
Will fail because the `textContent` resolves to `Shownfalse`
**Why**:
React filters values from being displayed. This changes the text content builder to reflect that.
**How**:
By filtering out values react normally ignores.
**Checklist**:
=> feat: filter values normally hidden by React

extend-expect.d.ts
Update `Matchers` types due to @types/jest breaking change
**What**:
Fix an issue where autocomplete doesn't work properly in `*.[test|spec].tsx` files
**Why**:
Keep the interfaces up-to-date with @types/jest
**How**:
Set `Matchers` interface generic types as `<R, T>`
**Checklist**:
Fixes #25, fixes #21
=> fix: Update Matchers types

README.md, src/__tests__/to-have-prop.js, src/to-have-prop.js, src/utils.js
**What**:
when using the latest @testing-library/react-native version, the function `toHaveProp(attr: string, value?: any)` doesn't work properly when getting the element *by text*, it checks for the prop existence but does not compare to the expected value, when given, and returns 'pass' even if the expected value is wrong.
**Why**:
to be able to work with this function using the new version of @testing-library/react-native
**How**:
just changed a couple of row in to-have-props.js
**Checklist**:
to recreate the issue, you can checkout this [branch](https://github.com/khealth/jest-native/tree/recreate_toHaveProp_bug)
=> fix: toHaveProp func to work with @testing-library/react-native latest version (7.0.2)

package.json
**What**:
This PR is an attempt to fix breaking snapshot tests on master.
**Why**:
Looks like travis has a different output color when running jest on master as discussed in #42, so it's breaking snapshot tests. 
**How**
Running jest with `--colors` might fix.
**Checklist**:
=> chore: run jest with --colors

src/__tests__/__snapshots__/to-have-style.js.snap, src/__tests__/to-have-style.js
**What**:
Reimplement the snapshot tests for `toHaveStyle`
**Why**:
See discussion here:
https://github.com/testing-library/jest-native/commit/f0f434643b3b54da7be242660dc4a34b5efc9cfa#r42121221
**tl;dr** @brunohkbx discovered a problem running the tests with snapshots as part of #26 , so let's isolate this change to more effectively debug. Testing the output diff is important as it's key feedback users rely on when a test fails.
**Checklist**:
=> test: snapshot toHaveStyle diff output

README.md, src/__tests__/to-have-text-content.js, src/to-have-text-content.js
BREAKING CHANGE: toHaveTextContent may produce more output in some cases due to including all nested sibling elements
**What**:
`toHaveTextContent` currently supports recursion, but it would only handle the first child element of a deeply nested child.
This existing test would of course pass:
https://github.com/testing-library/jest-native/blob/master/src/__tests__/to-have-text-content.js#L50-L63
But add a sibling element to the nested `View` and it would fail to include the ` additional text ` of said element. In this example, it would receive: `Step 1 4`
```js
<Text testID="parent">
<Text>Step</Text>
<Text> 1 </Text>
<View>
<Text> of </Text>
<Text> additional text </Text> // <-- toHaveTextContent would never parse this 
</View>
4
</Text>
```
**Why**:
`toHaveTextContent` should parse all …
=> feat(breaking): toHaveTextContent supports nested arrays of sibling elements

src/__tests__/to-be-disabled.js, src/to-be-disabled.js
**What**:
`TouchableNativeFeedback` wasn't included in the list of components that have a `disabled` prop. As such, `toBeDisabled` would always return `false`.
**Why**:
Because Android is important too 😄 
**How**:
Simply added `TouchableNativeFeedback` to the allow list of components.
**Checklist**:
[docs](https://github.com/testing-library/jest-native/README.md) — N/A
=> fix: Fix toBeDisabled for TouchableNativeFeedback

README.md
**What**:
It fixes a wrong link in the setup instructions. Resolves #55
=> docs: fix wrong link

.github/workflows/validate.yml
**Why**:
It was missing in .github/workflows/validate.yml
=> chore(ci): add missing env section

src/__tests__/to-have-text-content.js, src/to-have-text-content.js
**What**:
Fix a bug where text content that gets split into an array does not get evaluated by the `toHaveTextContent` matcher.
**Why**:
There's a test case in the PR, but this test case currently fails in master:
```
const variable = 'variable';
const { container } = render(<Text>With a {variable}</Text>);
expect(container).toHaveTextContent('With a variable');
// Expected element to have text content:
// With a variable
// Received:
```
**How**:
The bug was in treating all array elements as react nodes that had a path of `['props', 'children']` that could be traversed to get the text content. The fix is to pass the element directly into the recursive `getText` call and let the conditional logic determine how to extract the text.
**Checklist**: …
=> fix: toHaveTextContent supports interpolated variables

src/__tests__/to-have-prop.js, src/to-have-prop.js
**What**:
This PR fixes the matcher toHaveProp
**Why**:
It wasn't  possible to check for null values
**Checklist**:
=> fix(toHaveProp): check null values

package.json, src/to-be-disabled.js, src/to-be-empty.js, src/to-contain-element.js, src/to-have-prop.js, src/to-have-style.js, src/to-have-text-content.js
Import directly the function to avoid jest creating a context for all the ramda utilities
**What**:
Import directly the ramda functions instead of the global index
**Why**:
Jest create a virtual machine for every imported file in order to provide a secure context. this has been reported in different jest issues 
- https://github.com/facebook/jest/issues/7963
- https://github.com/facebook/jest/issues/11234
profiling my project i see that 500ms is spent in everyfile due to the `setupFilesAfterEnv` https://jestjs.io/docs/configuration#setupfilesafterenv-array
and this is mainly because jest is creating a vm for each ramda function file
This has a tradeoff as it's a bit of incovenience for the mantainers but as this library is very linked to jest, i feel is interesting to pay this small code …
=> perf(ramda): Use individual imports

src/__tests__/to-have-text-content.js, src/to-have-text-content.js
**What**:
I've fixed #60 but this also cover the fixes from #59 (I've also **copied** the PR author test... but if the author wishes to merge his changes first and then have me apply my changes  and rewrite this PR I can do it)
I've also added a missing test to assure that `toHaveTextContent` fails when it should
**Why**:
Described in #60, but to summarize: `toHaveTextContent` wasn't collecting properly children nodes to find text
**How**:
I've made a simple recursive function that transverses all children collecting text childs and join them for the match comparison
**Checklist**:
* I've only used ramda compositions because this project seems to be using ramda, but if you wish I can rewrite things without ramda.
* For another PR: I would recommend using babel-transform-imports for ramda …
=> fix: toHaveTextContent collect properly text of children nodes

src/to-be-disabled.js, src/to-be-empty.js, src/to-contain-element.js, src/to-have-prop.js, src/to-have-style.js
**What**:
Importing Jest Native in projects based on Node 14+ results in following error:
```
ENOENT: no such file or directory, open '/Users/maciej/Dev/react-native-testing-library/examples/basic/node_modules/ramda/src/compose'
at Runtime.readFile (node_modules/jest-runtime/build/index.js:2574:21)
at Object.<anonymous> (node_modules/@testing-library/jest-native/dist/to-be-disabled.js:9:39)
```
**Why**:
Under node 14 the `.js` file extensions seems necessary in case of Ramda. Probably due to some technicalities of how Ramda export these. Note that Ramda does not seem maintained lately.
**How**:
App '.js' file extension to Ramda imports
**Checklist**:
=> fix: update ramda imports

.github/workflows/validate.yml, package.json, src/to-contain-element.js, src/to-have-style.js
**What**:
Update all primary deps to the newest versions.
Also needed to update node versions from 12 + 14, to 14 + 16 + 18, as RN 0.69 no longer supports Node 12:
```
error react-native@0.69.4: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.1"
```
Also had to update `ramda/src/xxx` imports to `ramda/src/xxx.js`, as these first stopped working under node 16.
**Why**:
Time go by, we need to make sure we work with the current versions of React, React Native, RN Testing Library, Jest, etc
**How**:
Manually updated deps and verified that all tests pass.
**Checklist**:
Resolves #76, resolves #43,
=> chore: update deps

src/to-be-disabled.js, src/to-be-empty.js, src/to-contain-element.js, src/to-have-prop.js, src/to-have-style.js
**What**:
Tweaking of Ramda imports in #82 has caused issues for some users. This PR is reverting that change.
**Why**:
User complained that Ramda import from Jest Native is failing with following error:
**How**:
Replace imports from `ramda/src/xxx.js` with `{ xxx } from 'ramda';
**Checklist**:
=> fix: revert tweaked ramda imports

package.json, src/__tests__/utils.js, src/to-be-disabled.js, src/to-be-empty.js, src/to-contain-element.js, src/to-have-prop.js, src/to-have-style.js, src/utils.js
**What**:
Remove Ramda dependency and replace with plain JS method where possible. 
Resolves #97 
**Why**:
Ramda has affected performance of Jest tests due to badly implemented treeshaking, and attempt #79  to optimise it using custom imports have caused issues for some users.
**How**:
Refactor to use plain JS:
Migration:
**Checklist**:
=> refactor: remove `ramda` dependency

.github/workflows/validate.yml, extend-expect.d.ts, package.json, src/__tests__/to-contain-element.js, src/__tests__/to-have-prop.js, src/utils.js
**What**:
Setup ESLint validation with reasonable rules. Fix remaining rule violations.
Also:
- switch to plain Yarn because of install issues with NPM & npm-install action (no noticable perf impact on CI runs)
**Why**:
Extra safety net on the CI for code quality assurance. 
**How**:
* Added eslint deps
* Set reasonable rules based on RNTL rules
* Added linter step to GH action
**Checklist**:
=> chore: eslint setup

README.md, src/__tests__/__snapshots__/to-have-style.js.snap, src/__tests__/to-have-style.js, src/__tests__/utils.js, src/to-have-style.js, src/utils.js
**What**:
Closes https://github.com/testing-library/jest-native/issues/109
**Why**:
`ramda` was removed on [v4.0.11](https://github.com/testing-library/jest-native/releases/tag/v4.0.11) which introduced a different behavior compared to what we had in the past, removing the ability of handling nested arrays as the style prop.
**How**:
Simply replacing `mergeAllStyles` by `StyleSheet.flatten` (from `react-native` itself)
**Checklist**:
=> fix: toHaveStyle nested arrays

src/__tests__/__snapshots__/to-be-visible.tsx.snap, src/utils.ts
**What**:
Improve element formatting in output messages:
Before:
```
Received element is visible:
Object {
"props": Object {
"children": undefined,
"testID": "test",
},
}
```
After:
```
Received element is visible:
<View
testID="test"
/>
```
**Why**:
Improve readability for printed element
**How**:
Persuade ReactTestComponent plugin to pretty-format package that passed element is `ReactTestRendererJSON` instance, so that if formats it as JSX.
**Checklist**:
[docs](https://github.com/testing-library/jest-native/README.md) N/A
=> fix: improve element formatting

extend-expect.d.ts
**What**:
`extend-expect.d.ts` is using `StyleProp` type, but this type is not imported. It causes TS error when library is using with other TypeScript projects.
**Why**:
To have error-free TS parser.
**How**:
By updating TS definition file.
**Checklist**:
=> fix: Add missing StyleProp type in TS definition file

extend-expect.d.ts, src/__tests__/to-have-accessibility-value.tsx, src/extend-expect.ts, src/to-have-accessibility-value.ts
**What**:
Matcher for matching accessibility value.
**Why**:
Current `toHaveProp` is performing strict matching of `accessibilityValue` prop, while matching based only on some a11y value entries is useful.
**How**:
Matching code based on `*ByA11yValue` matcher.
**Checklist**:
@pierrezimmermannbam, @AugustinLF, @MattAgn could you help with reviewing this?
=> feat: toHaveAccessibilityValue() matcher

README.md
**What**:
Add missing docs for toHaveAccessibilityValue() matcher
**Checklist**:
=> chore: add missing docs for toHaveAccessibilityValue() matcher

src/__tests__/component-tree.tsx, src/__tests__/to-be-visible.tsx, src/__tests__/to-have-style.tsx, src/component-tree.ts, src/to-be-visible.ts
**What**:
Fixes https://github.com/testing-library/jest-native/issues/133
To fix an error when `.toBeVisible` is used on a Pressable using a function for the `style` prop
**Why**:
Using a function is a documented use case ([doc](https://reactnative.dev/docs/pressable#style)) and so it should be supported.
**How**:
By adding a check if the style prop is a function and calling it with `{ pressed: false }` as a default value.
**Checklist**:
=> fix: .toBeVisible error with Pressable function style

README.md, src/__tests__/to-be-disabled.tsx, src/to-be-disabled.ts
**What**:
`toBeDisabled` and `toBeEnabled` matcher will now look at the `editable` prop from the `TextInput` component
**Why**:
`TextInput` does not have a `disabled` props but a `editable` to enable or disable it. The only way to test if it is truly disabled is through `editable`
**How**:
Added a supplementary check in `isElementDisabled` function
**Checklist**:
=> fix: support TextInput editable={false} prop check in isEnabled/isDisabled matchers

legacy-extend-expect.d.ts, legacy-extend-expect.js, package.json, src/__tests__/legacy-extend-expect.tsx, src/legacy-extend-expect.ts, tsconfig.json
**What**:
This PR is exposing alternative `legacy_toXxx` matcher naming, in order to support ongoing migration of Jest Native matchers to RNTL, so that users can use both new RNTL matchers and legacy Jest Native matchers to gradually migrate their code. 
This PR is not doing advertising this change yet, as the RNTL migration is ongoing. I would add relevant documentation when RNTL matchers are read.
**Why**:
This is needed as migrated matchers are usually named the same as Jest Native matchers, so without this there would be a naming clash.
**How**:
Add `legacy-extend-expect` export, so which extends `expect` with `legacy_toXxx` matchers rather than typically `toXxx` naming. The original `extend-expect` remains still available, so existing users should not be affected.
**Checklist**:
=> refactor: expose legacy extend-expect

README.md
**What**:
I have updated the correct links to Jest Matchers docs and migration guide 
**Why**:
The existing links returns 404 page in RNTL 
**How**:
Updated the Readme file with correct links 
**Checklist**:
=> [docs] Updated correct links to Jest Matchers docs and migration guide in readme file
